### Checking the processing speed of python list vs numpy array

In [2]:
import time
import numpy as np

vector_size = 10000

def python_version():
    t1 = time.time()
    X = range(vector_size)
    Y = range(vector_size)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(vector_size)
    Y = np.arange(vector_size)
    Z = X + Y
    return time.time() - t1


t1 = python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.002895832061767578 0.00034499168395996094
Numpy is in this example 8.393918451969592 faster!


np.array to convert/create a list object into a numpy array object

In [3]:
array1 = np.array([1, 4, 2, 5, 3])

In [4]:
array2 = np.array([3.14, 4, 2, 3])

In [5]:
array3 = np.array([[1,2,3],[4,5,6]])

In [6]:
array4 = np.array([1, 2, 3, 4], dtype='float32')

In [7]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1.3, 3.4, 5.6, 7.8])

display(a)
display(b)

array([1, 2, 3, 4])

array([1.3, 3.4, 5.6, 7.8])

### Converting python list to numpy array

In [8]:
a = [(1,2,3), (4, 5, 6)]
display(a)
display(type(a))

b = np.array(a)
display(b)
display(type(b))

[(1, 2, 3), (4, 5, 6)]

list

array([[1, 2, 3],
       [4, 5, 6]])

numpy.ndarray

In [9]:
a = np.zeros((2,2))   # Array of all zeros

In [10]:
b = np.ones((1,2))    # Array of all ones

In [11]:
c = np.full((2,2), 7)  # Constant array

In [12]:
d = np.eye(2)         # Create a 2x2 identity matrix

In [13]:
e = np.random.random((2,2))  # Array filled with random values

### Attribute of Arrays

In [14]:
x1 = np.random.randint(10, size=6) # One-dimensional array

In [15]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array

In [16]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [17]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


### Indexing of Arrays

In [18]:
a = np.arange(10)**3

display(a)
display(a[2])
display(a[2:5])
display(a[-5:-2])

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

8

array([ 8, 27, 64])

array([125, 216, 343])

Create the following rank 2 array with shape (3, 4)

In [19]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
display(a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Use slicing to pull out the subarray consisting of the first 2 rows, and columns 1 and 2; b is the following array of shape (2, 2)

In [20]:
b = a[:2, 1:3]
display(b)

array([[2, 3],
       [6, 7]])

A slice of an array is a view into the same data, so modifying it will modify the original array

In [21]:
display(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
display(a[0, 1])   # Prints "77"

2

77

### One Dimensional

In [22]:
display(x1)

array([8, 3, 9, 3, 5, 4])

In [23]:
display(x1[0])
display(x1[4])

8

5

In [24]:
x1[0] = 3.14159 # this will be truncated!x1

x1[:5] # first five elements

x1[5:] # elements after index 5

x1[4:7] # middle subarray

x1[::2] # All rows and till column index 2

x1[::]  # All rows All Columns

array([3, 3, 9, 3, 5, 4])

In [25]:
display(x2)

display(x2[:2, :3]) # two rows, three column

display(x2[:3, ::2]) # all rows, every other column

display(x2[0, :]) # first row of x2

display(x2[0, :])
display(x2[0, ::])
display(x2[0, 0:4:1])

array([[5, 7, 0, 8],
       [6, 3, 0, 8],
       [5, 6, 3, 5]])

array([[5, 7, 0],
       [6, 3, 0]])

array([[5, 0],
       [6, 0],
       [5, 3]])

array([5, 7, 0, 8])

array([5, 7, 0, 8])

array([5, 7, 0, 8])

array([5, 7, 0, 8])